### ISSUE TITLE
Eclipse JUnit5 NoClassDefFoundError

### ISSUE THREAD

**Issue by sdhawley** [iboyko/gradle-plugins#19]
I was having problem with running Junit test from the eclipse junit test runner, no class def found error. I noticed I could set the classpath in the test runner configuration which resolved the issue, so I poked around a little more and found that even though jpaModelgen output was in classpath it wasn't included in the gradle test scope, adding test to the gradle used by scope fixes the problem (without having to modify the classpath of the run configuration).
```
<classpathentry kind="src" output="bin/jpaModelgen" path="src/jpaModelgen/java">
   <attributes>
      <attribute name="gradle_scope" value="jpaModelgen"/>
      <attribute name="gradle_used_by_scope" value="jpaModelgen,test"/>
   </attributes>
</classpathentry>
```
I'm not sure if this is the best way to fix or which plugin should be responsible for it, but if it helps anybody this worked for me.

Any idea how to get this to happen automatically?

**Comment by iboyko** [comment]
Please tell me more about your Java, Eclipse, Gradle and Buildship versions. 

When you use the Buildship version greater equals 2.2.0, please try to add follows to you Gradle Build file to fix the problem:
`
project.afterEvaluate {
    sourceSets {
        test {
            runtimeClasspath += sourceSets.jpaModelgen.output
        }
    }
}
`

Please notify me about the result...

**Comment by sdhawley** [comment]
Adding that to my build file causes compile to fail in the generated sources:
```
error: cannot find symbol public static volatile SingularAttribute<ResourceAccount, String>
```
But it does add the test scope to the jpaModelgen classpath entry.

gradle 4.6
groovy 2.4.12
buildship 2.2.1
eclipse Oxygen.3 Release (4.7.3) Build id: 20180308-1800
java-1.8.0-openjdk.x86_64                      1:1.8.0.161-5.b14.fc27

**Comment by iboyko** [comment]
It was possible for me to get NoClassDefFoundError im [jpamodelgen-sample](https://github.com/iboyko/gradle-plugins/tree/master/samples/jpamodelgen-sample) Projekt with JUnit5. 
jpamodelgen-plugin v1.1.4
Gradle 4.6
JUnit5 5.1.0
Eclipse 4.7.3
Buidship 2.2.1
Java 1.8.0_151

After applying of configuration code from my last comment, the exception disappeared and test ran. 

jpamodelgen-sample/build.gradle
```
buildscript {
	repositories {
		mavenCentral()
	}
	dependencies {
		classpath 'org.junit.platform:junit-platform-gradle-plugin:1.1.0'
	}
}

//Real project configuration:
plugins {
    id 'java'
    id 'eclipse'
    id "at.comm_unity.gradle.plugins.jpamodelgen" version "1.1.4"
}

apply plugin: 'org.junit.platform.gradle.plugin'

ext.junit4Version        = '4.12'
ext.junitVintageVersion  = '5.1.0'
ext.junitPlatformVersion = '1.1.0'
ext.junitJupiterVersion  = '5.1.0'

int javaVersion = Integer.valueOf((String) JavaVersion.current().getMajorVersion())
if (javaVersion < 10) apply plugin: 'jacoco'

repositories{
    jcenter()
}

test {
	useJUnitPlatform {
		// includeEngines 'junit-jupiter', 'junit-vintage'
		// excludeEngines 'custom-engine'

		// includeTags 'fast'
		excludeTags 'slow'
	}
	
	if (javaVersion < 10) finalizedBy jacocoTestReport
}

jpaModelgen{
    jpaModelgenSourcesDir = 'src/generated/java'
}

compileJpaModelgen {
    includes += ['**/entities/*.java', '**/entity/*.java']
}

dependencies {
    compile 'org.hibernate:hibernate-entitymanager:4.3.8.Final'
    compileOnly 'org.projectlombok:lombok:1.16.18'

    // JUnit Jupiter API and TestEngine implementation
    testCompile("org.junit.jupiter:junit-jupiter-api:${junitJupiterVersion}")
    testRuntime("org.junit.jupiter:junit-jupiter-engine:${junitJupiterVersion}")

    testCompile("junit:junit:${junit4Version}")
    testRuntime("org.junit.vintage:junit-vintage-engine:${junitVintageVersion}") {
	because 'allows JUnit 3 and JUnit 4 tests to run'
    }
    testRuntime("org.junit.platform:junit-platform-launcher:${junitPlatformVersion}") {
        because 'allows tests to run from IDEs that bundle older version of launcher'
    }
}

wrapper {
  gradleVersion = "4.6"
}
```

**Comment by sdhawley** [comment]
The issue seems to be resolved with recent versions of eclipse and gradle. If I notice the problem again I'll update, but for now I'll close this issue.
