### ISSUE TITLE
1.1.1 isn't available

### ISSUE THREAD

**Issue by juergenzimmermann** [iboyko/gradle-plugins#2]
When you look at https://bintray.com/iboyko/gradle-plugins/jpamodelgen-plugin/view you cannot find version 1.1.1.

**Comment by iboyko** [comment]
Version is uploaded to
https://bintray.com/iboyko/gradle-plugins/jpamodelgen-plugin/1.1.1/view.

Bintray repository is deprecated. Please use gradle plugin repository.
