### ISSUE TITLE
Need to pass arguments to java compiler

### ISSUE THREAD

**Issue by gallonfizik** [iboyko/gradle-plugins#4]
I am developing on Windows with RU locale, so i get messages like this:
`:initJpaModelgenSourcesDir
D:\Work\soft-e\Center2_Server\src\main\java\ru\softengineering\Sigma\misc\ReflectionUtils.java:103: error: unmappable character for encoding Cp1251
    // Р?С‰РµРј РЅР°С€ РїР°СЂР°РјРµС‚СЂ СЃСЂРµРґРё РІСЃРµС… РїР°СЂР°РјРµС‚СЂРѕРІ С‚РѕРіРѕ РєР»Р°СЃСЃР°, РіРґРµ РѕРїСЂРµРґРµР»РµРЅ РЅСѓР¶РЅС‹Р№ РЅР°Рј РїР°СЂР°РјРµС‚СЂ.`

In files that are not processed by jpamodelgen this issue is fixed by setting `compileJava.options.encoding = 'UTF-8'` while having source files UTF-8-encoded, of course.

So I guess passing a `-encoding UTF-8` to javac from jpamodelgen would suffice to fix this.

**Comment by iboyko** [comment]
You can try to use 
```
tasks.withType(Compile) {
    options.encoding = 'UTF-8'
}
```
it will set encoding to all java compile tasks.
http://mrhaki.blogspot.co.at/2012/06/gradle-goodness-set-java-compiler.html

**Comment by gallonfizik** [comment]
Thank you, that seems like totally resolving my issue. Weird that i googled for a solution but didn't find this one. Sorry for your trouble.
