### ISSUE TITLE
compileOnly dependencies aren't recognized

### ISSUE THREAD

**Issue by shot-mk** [iboyko/gradle-plugins#5]
Hi,
I have a compileOnly dependency in a project on javax.servlet-api. It was working well with build since i am using gradle 3.3. I've added your plugin in my build and now it is failing on compileJpaModelgen task with ClassNotFound errors for javax.servlet classes. I think this task somehow do not respect compileOnly dependencies... May be i am missing some configurations.. 
Will appreciate any help.
Thanks.

**Comment by shot-mk** [comment]
After little research it seems that i found how to resolve this issue. 
You have in JpaModelgenCompile class at  line 31 : 
`setClasspath(project.configurations.compile)`
and according to [this](https://blog.gradle.org/introducing-compile-only-dependencies)
it should be something like : 
`setClasspath(project.configurations.compileClasspath)`

**Comment by iboyko** [comment]
Thanks for your research, I'll try it out.

**Comment by shot-mk** [comment]
I've already tried this, and seems that this solves the issue. Was going to make pull request, but if u are already working on this, i think i will just wait for your update, without doing pull request for such a small change :D Thanks for fast reply.

**Comment by iboyko** [comment]
Please add the pull request, I have not time to work on this project till tomorrow. Thanks!

**Comment by iboyko** [comment]
New version is published to gradle repository.
https://plugins.gradle.org/plugin/at.comm_unity.gradle.plugins.jpamodelgen
Thanks for you help

**Comment by monrealis** [comment]
This change https://github.com/iboyko/gradle-plugins/commit/03f6ef9b6331c541337d09b84483f37d8cca29f9 was unfortunately overridden by https://github.com/iboyko/gradle-plugins/commit/bec2818293c87ac83612be0129c9ca58023aea10#diff-54aedaef2683ea23ee13d4b738b311cd

**Comment by monrealis** [comment]
If someone could change back `compile` to `compileClasspath` and release a version, it would be great!
