### ISSUE TITLE
Unable to integrate this plugin with lombok

### ISSUE THREAD

**Issue by vovarova** [iboyko/gradle-plugins#9]
I think it is because of this option 
compileJava.options.compilerArgs += ["-proc:none"]
because lombok has also Annotation Processor

**Comment by krzysztofkominiaksolsoft** [comment]
@iboyko When do you plan to resolve this issue? 
We want to start new project using your plugin, but we also want to use Lombok...

**Comment by iboyko** [comment]
Thanks to @chrisN777 is the new plugin version now available at Gradle Repository.
I hope it will solve your lombok issue.

**Comment by kksoft** [comment]
So ```compileJava.options.compilerArgs += ["-proc:none"]``` is no longer needed at the end of the build file?

**Comment by chrisN777** [comment]
Correct. ^^
